apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qev7odaaq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qev7odaaq-python 
  name: qev7odaaq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qev7odaaq-python 
